### ISSUE TITLE
Error en el momento de validar factura Odoo 10

### ISSUE THREAD

**Issue by juahidma** [CRLibre/fe-hacienda-cr-odoo#108]
Impacted versions: Version 10 Community Edition 

Steps to reproduce: Se realiza la instalación con los pasos que indica en el Wiki, en el ultimo paso que es presionar el botón de validar la factura aparece el siguiente mensaje 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 899, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\cr_electronic_invoice\models\electronic_invoice.py", line 897, in action_invoice_open
TypeError: __init__() takes exactly 2 arguments (3 given)

Current behavior: La factura no se puede aplicar ya que la deja en estado borrador 

Expected behavior: Al presionar el botón de validar se espera que se genere el consecutivo de la factura. 

Video/Screenshot link (optional):

**Comment by juahidma** [comment]
Hola actualice a la ultima versión, pero ahora en el momento de validar cambio al siguiente error: 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 899, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\cr_electronic_invoice\models\electronic_invoice.py", line 974, in action_invoice_open
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 34: ordinal not in range(128)

**Comment by juahidma** [comment]
Hola logre que funcionara en el archivo electronic_invoice.py en las lineas de los errores elimine los acentos y caracteres especiales, reinicie el servicio de Odoo, y logre saber porque no podía validar la factura, ya que uno de los metodos de pago le faltaba un dato en terminos de pago cuando es pago en efectivo, en resumidas cuentas el error se encuentra en el momento de desplegar los errores a los usuarios debido a los caracteres especiales. 

Saludos

**Comment by cewongq** [comment]
Excelente!
Muchas gracias por el aporte. Ya se está agregando la solución a ese problema.

**Comment by ingjorgearias** [comment]
HOLA BUENAS TARDES. 

yo sigo con este mismo problema he reinstalado los módulos y hacer cada paso pero sigo teniendo el mismo problema, sera que alguno me puede dar una ayuda con mi sistema para validar cual es el problema. 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 899, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\cr_electronic_invoice\models\electronic_invoice.py", line 862, in action_invoice_open
TypeError: __init__() takes exactly 2 arguments (3 given)


he realizado tambien la busqueda en las lineas pero no veo el inconveniente.
