### ISSUE TITLE
Error instalando cr_electronic_invoice en una base de datos limpia

### ISSUE THREAD

**Issue by Alukarl** [CRLibre/fe-hacienda-cr-odoo#122]
Impacted versions: 11

Steps to reproduce: Instalar modulo cr_electronic_invoice

Current behavior: La instalación no se realiza y no muestra ningún cuadro de error.

Expected behavior: Instalar el modulo en una base de datos limpia sin errores.

odoo log:

```bash
2019-02-02 19:18:02,963 3518 INFO ? werkzeug: 10.49.254.2 - - [02/Feb/2019 19:18:02] "POST /longpo
lling/poll HTTP/1.1" 500 -
2019-02-02 19:18:02,967 3518 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unpr
oxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1297, in __call__
    self.load_addons()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1319, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load

  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked

  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible

  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>

  File "/opt/custom-addons/cr_electronic_invoice/models/__init__.py", line 3, in <module>
    from . import electronic_invoice
File "/opt/custom-addons/cr_electronic_invoice/models/electronic_invoice.py", line 1007
    if taxes_lookup[i['id']]['tax_code'] <> '00':
                                          ^
SyntaxError: invalid syntax
```
Correccion sugerida:

```diff
--- electronic_invoice_original.py	2019-02-02 13:53:32.757070000 -0600
+++ electronic_invoice.py	2019-02-02 13:55:33.478795585 -0600
@@ -1004,7 +1004,7 @@
                         for i in inv_line.invoice_line_tax_ids:
                             taxes_lookup[i.id] = {'tax_code': i.tax_code, 'tarifa': i.amount}
                         for i in line_taxes['taxes']:
-                            if taxes_lookup[i['id']]['tax_code'] <> '00':
+                            if taxes_lookup[i['id']]['tax_code'] != '00':
                                 tax_index += 1
                                 tax_amount = round(i['amount'], 5)*quantity
                                 impuesto_linea += tax_amount
@@ -1171,4 +1171,4 @@
 
                     else:
                         raise UserError('Debe configurar correctamente la secuencia del documento')
-   
\ No hay ningún carácter de nueva línea al final del fichero
```

**Comment by jaullo** [comment]
Hola @Alukarl gracias por el reporte. Ese error precisamente lo vimos en días pasados y estamos trabajando en la solución. A inicios de la próxima semana se subirá la corrección

**Comment by Alukarl** [comment]
Con el ultimo commit el error se soluciono, gracias
