### ISSUE TITLE
Error instalación Odoo 11

### ISSUE THREAD

**Issue by brmad175** [CRLibre/fe-hacienda-cr-odoo#153]
Impacted versions: 11

Steps to reproduce: instalación cr_electronic_invoice siguiendo pasos -Requisitos para instalar el modulo de Facturación Electrónica para Costa Rica- wiki

Current behavior: error al instalar
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7fba5e9f5c80>, 'cr_electronic_invoice.model_account_invoice')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 643, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 728, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 734, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1349, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1338, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: cr_electronic_invoice.model_account_invoice

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 792, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 853, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 742, in parse
    self.parse(rec, mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 752, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 745, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 643, in _tag_record
    f_val = self.id_get(f_ref)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 728, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 734, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1349, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-21>", line 2, in xmlid_lookup
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 1338, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: cr_electronic_invoice.model_account_invoice" while parsing /usr/lib/python3/dist-packages/odoo/addons/cr_electronic_invoice/data/data.xml:4, near
-<record id="ir_cron_consultahacienda" model="ir.cron">
			<field name="name">Consulta Hacienda FE Clientes</field>
			<field name="model_id" ref="model_account_invoice"/>
			<field name="state">code</field>
			<field name="code">model._consultahacienda()</field>
			<field name="interval_number">5</field>
			<field name="interval_type">minutes</field>
			<field name="numbercall">-1</field>
			<field name="doall" eval="False"/>
		</record>

Al instalar el modulo cr_electronic_invoice tengo este error, los modulos que dependen ya estan instalados, mismo resultado en ubuntu y windows 10 en versiones limpias de odoo 11,

**Comment by WhiteTiger08** [comment]
Al bajar el código del módulo de facturación, ¿se aseguró que bajó el branch 11.0?

**Comment by brmad175** [comment]
Hola, si baje el branch para odoo 11. Algo importante es q si reinicio el servicio odoo con el modulo copiado en la carpeta addons (sin instalarlo), odoo deja de mostrar los menus y si elimino el modulo de addons y reinicio el servicio odoo vuelve a mostrar los menus. 

![captura](https://user-images.githubusercontent.com/50937726/58262369-656fa680-7d37-11e9-982f-ba0e57b7dcec.png)

**Comment by juahidma** [comment]
Lo mismo sucede en la version 10, tengo que regresar a una version anterior del modulo para que funcione, si utilizo el ultimo publicado, sucede que el menu de odoo se cuelga, como expone @brmad175

**Comment by WhiteTiger08** [comment]
Saludos, ¿pueden revisar el número de versión en el manifest para ver cuál tienen?

**Comment by darkestblue91** [comment]
A mi me dió ese error luego de seguir un tutorial en Internet [https://linuxize.com/post/how-to-deploy-odoo-11-on-ubuntu-18-04/](url) en el cual había dejado ya el servicio de Odoo corriendo cuando empezé a seguir los pasos del archivo GuiaInstalación.txt, desde la linea 14 "pip install suds-py3", es decir, los hice con Odoo ejecutandose, luego probé activar el modulo, probé todo, reinstalar las dependencias y nada.

Ya luego se me ocurrió que tal vez podía ser que Odoo hacía algun check de los modulos al arranque, y reinicié el servicio, desde eso funcionó perfecta la instalación del modulo.

No se si es cosa mía pero eso lo solucionó.

**Comment by juahidma** [comment]
> Saludos, ¿pueden revisar el número de versión en el manifest para ver cuál tienen?
> 
> Acabo de hacer una instalación desde cero en 11.0 y la facturación se instala bien.

En el manifest dice lo siguiente: 

	'name': 'Facturación electrónica Costa Rica',
	'version': '0.1',
	'author': 'CRLibre.org',
	'license': 'AGPL-3',
	'website': 'https://crlibre.org/',
	'category': 'Account',
	'description':
		'''
		Facturación electronica Costa Rica.
		''',
	'depends': ['base', 'account','product','sales_team','l10n_cr_country_codes','account_cancel'],
	'data': ['data/data.xml',
	         'data/code.type.product.csv',
	         'data/identification.type.csv',
	         'data/payment.methods.csv',
	         'data/reference.code.csv',
	         'data/reference.document.csv',
	         'data/sale.conditions.csv',
	         'data/product.uom.csv',
	         'data/account.tax.csv',
			 'data/sequence.xml',
			 'data/mail_template_data.xml',
			 'views/account_journal_views.xml',
			 'views/electronic_invoice_views.xml',
			 #'views/report_sales_invoice_qweb.xml',
	         'security/ir.model.access.csv',
	         ],
	'installable': True,

**Comment by brmad175** [comment]
> Saludos, ¿pueden revisar el número de versión en el manifest para ver cuál tienen?
> 
> Acabo de hacer una instalación desde cero en 11.0 y la facturación se instala bien.

Hola, yo vi q se actualizo la version a 11.0.2.0.0 y he intentado instalarlo pero tengo el mismo resultado, he probado en windows y ubuntu, he pensado que quiza pueda tratarse de dependencias no instaladas pero el mensaje que me da el odoo es external id not found..., parece un problema de vistas, por eso creo que se me va el menu cuando reinicio el odoo, he probado de todo, yo para la instalacion utilice el proceso que esta en nightly.odoo.com el de agregar repositorio e instalar y me funciona bien y lo hace todo automatico y rapido, pero no se si esto puede causar algun error a la hora de instalar el modulo, algo interesante es que el modulo de country codes y el currency adapter que son dependencias si se instalan bien el error lo da cuando intento instalar el de electronica que me da el error que puse arriba y si reinicio el odoo se desaparece el menu. he intentado con pip y pip3 probando suerte al instalar lo de la guia de instalacion pero no cambia el resultado, la instalacion que mencionas la realizaste en ubuntu?  haces los mismos pasos de la guia de instalacion o haces algunos diferentes?

**Comment by jaullo** [comment]
Cuales son los errores exactos que tienen. Recuerden que en 15 días versión 4.2 deja de funcioanr por lo que ya no estamos dedicando ningún esfuerzo
