### ISSUE TITLE
Error en POS

### ISSUE THREAD

**Issue by juahidma** [CRLibre/fe-hacienda-cr-odoo#75]
Estoy usando la version 10 CE, puedo realizar correctamente la facturación de clientes desde los modulos de ventas y contabilidad, pero dede el modulo de POS, me sale la siguiente leyenda en el momento de enviar la factura del POS al ERP Odoo.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 895, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 687, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 672, in call_kw_model
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\point_of_sale\models\pos_order.py", line 615, in create_from_ui
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\cr_pos_electronic_invoice\models\pos_electronic_invoice.py", line 61, in _process_order
KeyError: 'to_invoice'

También encontre que en el archivo pos_templates que esta en la ruta \cr_pos_electronic_invoice\views la ruta de scripts y css esta mala ya inician con /pos_electronic_invoice/ ... y deberian ser /cr_pos_electronic_invoice/

**Comment by jaullo** [comment]
El POS aún está en proceso de desarrollo por lo que se pueden obtener errores inesperados
