### ISSUE TITLE
Error al Instalar en Odoo 10

### ISSUE THREAD

**Issue by leamormo** [CRLibre/fe-hacienda-cr-odoo#97]
Utilice el botón "Copiar" para informar al servicio de asistencia del error.

Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 1100, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1059, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Modelo no encontrado: res.country.county

Contexto del error:
Vista `res.country.county.form`
[view_id: 952, xml_id: n/a, model: res.country.county, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3803, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3257, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3401, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1104, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nModelo no encontrado: res.country.county\n\nContexto del error:\nVista `res.country.county.form`\n[view_id: 952, xml_id: n/a, model: res.country.county, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3803, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3257, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3401, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1104, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

Modelo no encontrado: res.country.county

Contexto del error:
Vista `res.country.county.form`
[view_id: 952, xml_id: n/a, model: res.country.county, parent_id: n/a]
None" while parsing /odoo/odoo-server/addons/l10n_cr_country_codes/views/country_codes_views.xml:4, near
<record id="view_res_country_county_form" model="ir.ui.view">
			<field name="name">res.country.county.form</field>
			<field name="model">res.country.county</field>
			<field name="arch" type="xml">
				<form string="Cantón">
					<sheet string="Cantón">
						<group col="4">
							<field name="code"/>
							<field name="name"/>
							<field name="state_id"/>
						</group>
					</sheet>
				</form>
			</field>
		</record>

**Comment by jaullo** [comment]
Favor descargar la ultima version

**Comment by leamormo** [comment]
continua el generando error al instalar.



Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 1100, in _validate_fields
    check(self)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1059, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Modelo no encontrado: res.country.county

Contexto del error:
Vista `res.country.county.form`
[view_id: 1020, xml_id: n/a, model: res.country.county, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3803, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3257, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3401, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1104, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error mientras se validaban las restricciones\n\nModelo no encontrado: res.country.county\n\nContexto del error:\nVista `res.country.county.form`\n[view_id: 1020, xml_id: n/a, model: res.country.county, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 938, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 442, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 535, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 426, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 318, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 224, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 754, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 3803, in _load_records
    records = self.create([data['values'] for data in to_create])
  File "<decorator-gen-32>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 425, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3540, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3257, in write
    self._write(store_vals)
  File "/odoo/odoo-server/odoo/models.py", line 3401, in _write
    self._validate_fields(vals)
  File "/odoo/odoo-server/odoo/models.py", line 1104, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error mientras se validaban las restricciones

Modelo no encontrado: res.country.county

Contexto del error:
Vista `res.country.county.form`
[view_id: 1020, xml_id: n/a, model: res.country.county, parent_id: n/a]
None" while parsing /odoo/odoo-server/addons/l10n_cr_country_codes/views/country_codes_views.xml:4, near
<record id="view_res_country_county_form" model="ir.ui.view">
			<field name="name">res.country.county.form</field>
			<field name="model">res.country.county</field>
			<field name="arch" type="xml">
				<form string="Cantón">
					<sheet string="Cantón">
						<group col="4">
							<field name="code"/>
							<field name="name"/>
							<field name="state_id"/>
						</group>
					</sheet>
				</form>
			</field>
		</record>

**Comment by leamormo** [comment]
ontexto del error:
Vista `res.country.county.form`
[view_id: 1020, xml_id: n/a, model: res.country.county, parent_id: n/a]
None" while parsing /odoo/odoo-server/addons/l10n_cr_country_codes/views/country_codes_views.xml:4, near
<record id="view_res_country_county_form" model="ir.ui.view">
			<field name="name">res.country.county.form</field>
			<field name="model">res.country.county</field>
			<field name="arch" type="xml">
				<form string="Cantón">
					<sheet string="Cantón">
						<group col="4">
							<field name="code"/>
							<field name="name"/>
							<field name="state_id"/>
						</group>
					</sheet>
				</form>
			</field>
		</record>

**Comment by jaullo** [comment]
@leamormo Favor actualizar nuevamente
